### ISSUE TITLE
Please publish new version

### ISSUE THREAD

**Issue by ardalann** [rleenders/cassandra-migrate#16]
Problem: The template file fix ( https://github.com/rleenders/cassandra-migrate/pull/15 ) was merged over a year ago but isn't published yet.

**Comment by jsuarezatzendesk** [comment]
looking forward to the new published version, in the meantime i worked around it by installing it as a git dependency:

`npm install rleenders/cassandra-migrate#daa6b6e756ffa5df1f4eb7ac6a2a44ba20a24bda`

**Comment by rleenders** [comment]
sorry about the delay, the new version is now published
